const $=x=>document.getElementById(x),C={"가구":"🛏️ 🛋️ 🪑 🗄️ 🪞 🧺 🚪 🪟","소품":"🧸 🐰 📚 ☕ 🕯️ 🎀 💌 🎁 🕰️ 🪴 💡 🧴","장식":"🌷 🌸 ⭐ 🌙 ☁️ 🩷 ✨ 🍓 🍰 🫧","동물":"🐈 🐕 🐇 🐹 🐥"};let cat="가구",sel=null,z=10;
function tabs(){$("tabs").innerHTML="";Object.keys(C).forEach(k=>{let b=document.createElement("button");b.textContent=k;b.className=k==cat?"on":"";b.onclick=()=>{cat=k;tabs();items()};$("tabs").append(b)})}function items(){$("items").innerHTML="";C[cat].split(" ").forEach(i=>{let b=document.createElement("button");b.textContent=i;b.onclick=()=>add(i);$("items").append(b)})}
function choose(e){document.querySelectorAll(".placed").forEach(x=>x.classList.remove("selected"));sel=e;if(e)e.classList.add("selected")}function tf(e){e.style.transform=`translate(-50%,-50%) scaleX(${e.dataset.f||1}) scale(${e.dataset.s||1})`}
function drag(e){e.onpointerdown=v=>{choose(e);e.setPointerCapture(v.pointerId);let r=$("stage").getBoundingClientRect();e.onpointermove=q=>{e.style.left=Math.max(2,Math.min(98,(q.clientX-r.left)/r.width*100))+"%";e.style.top=Math.max(2,Math.min(98,(q.clientY-r.top)/r.height*100))+"%"};e.onpointerup=()=>{e.onpointermove=null;saveState()}}}
function add(i){let e=document.createElement("div");e.className="placed";e.textContent=i;e.dataset.s=1;e.dataset.f=1;e.style.zIndex=++z;e.style.left="50%";e.style.top="50%";drag(e);$("stage").append(e);choose(e);saveState()}
function sc(n){if(sel){sel.dataset.s=Math.max(.35,Math.min(2.5,+sel.dataset.s+n));tf(sel);saveState()}}$("small").onclick=()=>sc(-.15);$("big").onclick=()=>sc(.15);$("flip").onclick=()=>{if(sel){sel.dataset.f=-sel.dataset.f;tf(sel);saveState()}};$("front").onclick=()=>{if(sel){sel.style.zIndex=++z;saveState()}};$("back").onclick=()=>{if(sel){sel.style.zIndex=Math.max(1,+sel.style.zIndex-2);saveState()}};$("del").onclick=()=>{if(sel){sel.remove();sel=null;saveState()}};$("none").onclick=()=>choose(null);
function style(){$("wallBg").style.background=$("wall").value;$("floorBg").style.backgroundColor=$("floor").value;let m=$("mood").selectedIndex;$("room").style.filter=m==2?"brightness(.72) saturate(.85)":m==1?"sepia(.08) saturate(1.15)":"none";label();saveState()}["wall","floor","mood"].forEach(x=>$(x).oninput=style);function label(){let p=$("pair").value.trim(),a=$("a").value.trim(),b=$("b").value.trim();$("label").textContent=p||[a,b].filter(Boolean).join(" × ")||"OUR LITTLE ROOM"}["a","b","pair"].forEach(x=>$(x).oninput=()=>{label();saveState()});
$("photo").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{let d=document.createElement("div");d.className="placed photo";d.dataset.s=d.dataset.f=1;d.style.left="50%";d.style.top="45%";d.style.zIndex=++z;d.innerHTML=`<img src="${r.result}">`;drag(d);$("stage").append(d);choose(d);saveState()};r.readAsDataURL(f);e.target.value=""};
$("addMemo").onclick=()=>{let t=$("memo").value.trim();if(!t)return;let d=document.createElement("div");d.className="placed memo";d.dataset.s=d.dataset.f=1;d.style.left="50%";d.style.top="45%";d.style.zIndex=++z;d.textContent=t;drag(d);$("stage").append(d);choose(d);$("memo").value="";saveState()};$("sign").onchange=()=>{$("footer").style.display=$("sign").checked?"flex":"none";saveState()};$("reset").onclick=()=>{if(confirm("방을 비울까요?")){$("stage").innerHTML="";sel=null;saveState()}};
$("save").onclick=async()=>{choose(null);let c=await html2canvas($("capture"),{scale:2,backgroundColor:"#fff"}),a=document.createElement("a"),p=$("pair").value.trim()||"우리";a.download=`Dearly — ${p}의 작은 방.png`;a.href=c.toDataURL();a.click()};
function saveState(){try{localStorage.setItem("dearly_room_v1",JSON.stringify({wall:$("wall").value,floor:$("floor").value,mood:$("mood").selectedIndex,a:$("a").value,b:$("b").value,p:$("pair").value,sign:$("sign").checked,objs:[...document.querySelectorAll(".placed")].map(e=>({c:e.className.replace(" selected",""),h:e.innerHTML,l:e.style.left,t:e.style.top,z:e.style.zIndex,s:e.dataset.s,f:e.dataset.f}))}))}catch{}}
function restore(){try{let d=JSON.parse(localStorage.getItem("dearly_room_v1"));if(!d)return;$("wall").value=d.wall;$("floor").value=d.floor;$("mood").selectedIndex=d.mood;$("a").value=d.a;$("b").value=d.b;$("pair").value=d.p;$("sign").checked=d.sign;(d.objs||[]).forEach(o=>{let e=document.createElement("div");e.className=o.c;e.innerHTML=o.h;e.style.left=o.l;e.style.top=o.t;e.style.zIndex=o.z;e.dataset.s=o.s;e.dataset.f=o.f;tf(e);drag(e);$("stage").append(e)});$("footer").style.display=d.sign?"flex":"none"}catch{}}tabs();items();restore();style();